version: '3'
services:
  backend:
    build: .
    ports:
      - 5000:5000
    env:
      - PORT=5000
    health_check:
      type: http
      path: /health
      port: 5000
      initial_delay_seconds: 10
      period_seconds: 15